/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan3;

/**
 *
 * @author Alfan11
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bil1 = new javax.swing.JTextField();
        Bil2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pangkat = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TFHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kalkulator Tugas Akhir");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 230, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Bilangan 1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 70, 20);

        Bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bil1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bil1);
        Bil1.setBounds(80, 40, 180, 40);

        Bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bil2ActionPerformed(evt);
            }
        });
        jPanel1.add(Bil2);
        Bil2.setBounds(80, 90, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Bilangan 2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Operator");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 70, 20);

        pangkat.setBackground(new java.awt.Color(102, 102, 255));
        pangkat.setText("^");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        jPanel1.add(pangkat);
        pangkat.setBounds(10, 180, 60, 60);

        kali.setBackground(new java.awt.Color(102, 102, 255));
        kali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(290, 180, 60, 60);

        bagi.setBackground(new java.awt.Color(102, 102, 255));
        bagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bagi.setText(":");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(80, 180, 60, 60);

        plus.setBackground(new java.awt.Color(102, 102, 255));
        plus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel1.add(plus);
        plus.setBounds(220, 180, 60, 60);

        kurang.setBackground(new java.awt.Color(102, 102, 255));
        kurang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(150, 180, 60, 60);

        akar.setBackground(new java.awt.Color(102, 102, 255));
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        jPanel1.add(akar);
        akar.setBounds(360, 180, 60, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hasil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 260, 40, 20);

        TFHasil.setEditable(false);
        TFHasil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TFHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFHasilActionPerformed(evt);
            }
        });
        jPanel1.add(TFHasil);
        TFHasil.setBounds(10, 290, 420, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 450);

        setBounds(0, 0, 467, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void Bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bil2ActionPerformed

    private void TFHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFHasilActionPerformed

    private void Bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bil1ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        
        int hasilkali = bil1*bil2;
        
        TFHasil.setText(String.valueOf(hasilkali));
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        double bil1 = Integer.parseInt(Bil1.getText());
        double bil2 = Integer.parseInt(Bil2.getText());
        
        double hasilbagi = bil1/bil2;
        
        TFHasil.setText(String.valueOf(hasilbagi));
    }//GEN-LAST:event_bagiActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        
        int hasilplus = bil1+bil2;
        
        TFHasil.setText(String.valueOf(hasilplus));
    }//GEN-LAST:event_plusActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        
        int hasilkurang = bil1-bil2;
        
        TFHasil.setText(String.valueOf(hasilkurang));
    }//GEN-LAST:event_kurangActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(Bil1.getText());
        double bil2 = Integer.parseInt(Bil2.getText());
        
        double hasilakar = Math.sqrt(bil1);
        
        TFHasil.setText(String.valueOf(hasilakar));
    }//GEN-LAST:event_akarActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
        double bil1 = Double.parseDouble(Bil1.getText());
        double bil2 = Integer.parseInt(Bil2.getText());
        
        double hasilpangkat = Math.pow(bil1, bil2);
        
        TFHasil.setText(String.valueOf(hasilpangkat));
    }//GEN-LAST:event_pangkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bil1;
    private javax.swing.JTextField Bil2;
    private javax.swing.JTextField TFHasil;
    private javax.swing.JButton akar;
    private javax.swing.JButton bagi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
